name: Test Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  streamlit-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Streamlit app (headless test)
        run: |
          timeout 15m streamlit run app.py || echo "Streamlit run finished"
